// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgRsjen-U51SaBl-1l_N0PU5cGz-1yFs',
    appId: '1:82362756699:web:11ddc595da763c034ed97e',
    messagingSenderId: '82362756699',
    projectId: 'clisync-4bff7',
    authDomain: 'clisync-4bff7.firebaseapp.com',
    databaseURL: 'https://clisync-4bff7-default-rtdb.firebaseio.com',
    storageBucket: 'clisync-4bff7.firebasestorage.app',
    measurementId: 'G-3XKXD0WSHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCgRsjen-U51SaBl-1l_N0PU5cGz-1yFs',
    appId: '1:82362756699:android:11ddc595da763c034ed97e',
    messagingSenderId: '82362756699',
    projectId: 'clisync-4bff7',
    databaseURL: 'https://clisync-4bff7-default-rtdb.firebaseio.com',
    storageBucket: 'clisync-4bff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCgRsjen-U51SaBl-1l_N0PU5cGz-1yFs',
    appId: '1:82362756699:ios:11ddc595da763c034ed97e',
    messagingSenderId: '82362756699',
    projectId: 'clisync-4bff7',
    databaseURL: 'https://clisync-4bff7-default-rtdb.firebaseio.com',
    storageBucket: 'clisync-4bff7.firebasestorage.app',
    iosBundleId: 'com.example.clisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCgRsjen-U51SaBl-1l_N0PU5cGz-1yFs',
    appId: '1:82362756699:ios:11ddc595da763c034ed97e',
    messagingSenderId: '82362756699',
    projectId: 'clisync-4bff7',
    databaseURL: 'https://clisync-4bff7-default-rtdb.firebaseio.com',
    storageBucket: 'clisync-4bff7.firebasestorage.app',
    iosBundleId: 'com.example.clisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgRsjen-U51SaBl-1l_N0PU5cGz-1yFs',
    appId: '1:82362756699:web:11ddc595da763c034ed97e',
    messagingSenderId: '82362756699',
    projectId: 'clisync-4bff7',
    authDomain: 'clisync-4bff7.firebaseapp.com',
    databaseURL: 'https://clisync-4bff7-default-rtdb.firebaseio.com',
    storageBucket: 'clisync-4bff7.firebasestorage.app',
  );
}